name: build and test
on: [push, pull_request, workflow_dispatch]
jobs:

  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.3'
    - name: Run Go test
      run: go test -v ./

  build:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.3'
    - name: Run Go build
      run: go build -v ./
    - name: Upload bin
      uses: actions/upload-artifact@v2
      with:
        name: go_port_scanner
        path: ./go_port_scanner
        retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Run Go build
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.3'
    - name: Download bin
      uses: actions/download-artifact@v2
      with:
        name: go_port_scanner
        path: /home/runner/go/bin
    - name: Test binary
      run: chmod -R +x /home/runner/go/bin/ && go_port_scanner -h 8.8.8.8 -p 53